version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    target: gcr.io/band-program/db:latest
    
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - APP_PORT=$PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - .:/app  # 確保掛載整個專案
    target: backend
    # command: [ "bash", "./wait-for-it.sh", "db:3306", "--", "./migrate.sh" ]

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8080

volumes:
  db_data:


networks:
  app-network:
    # 定義專用網路
    driver: bridge
